# Site settings
title: Broccoli
email: bojanstef4@gmail.com
description: Marijuana At Your Fingertips
baseurl: "" # the subpath of your site, e.g. /blog
url: https://trybroccoli.com
download_button_url: https://bojan.xyz
email_subscribe_url: https://bojan.xyz/#

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/bojanstef
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/bojanstef
pinterest_url:
slack_url:
twitter_url: https://twitter.com/TryBroccoli

# Build settings
markdown: kramdown
